### ISSUE TITLE
keyword for found content

### ISSUE THREAD

**Issue by Jama1985hun** [clanceyp/link-audit#2]
Hello

I know this program is not supported anymore, but maybe you can help me.
Its working great, i just not found a good keyword to found "No longer accepting applications" on the linkedin site.
Attached the link to see it.
Can you help me how i can found it, what keyword will found it?

https://www.linkedin.com/jobs/view/senior-manu%C3%A1lis-tesztel%C5%91-at-otp-bank-magyarorsz%C3%A1g-3982450414/?originalSubdomain=hu

**Comment by clanceyp** [comment]
Sorry @Jama1985hun it looks like that content is added to the linkedin page dynamically, so there isn't anything in the source code to find. The extension only looks at the HTML from the server : (
